ALLOWED_TAGS = [
    "p", "h1", "h2", "h3", "h4", "h5", "h6",
    "ul", "ol", "li", "blockquote", "pre", "code",
    "strong", "em", "a", "img", "hr", "br", "table",
    "thead", "tbody", "tr", "th", "td", "div", "span",
    "svg", "circle", "line", "path", "rect", "polygon",
    "button", "defs", "clipPath", "g", "title", "style",
    "linearGradient", "stop", "figure", "figcaption", "video", "source"
]

ALLOWED_ATTRIBUTES = {
        "*": ["style", "class"],
    "h1": ["id"],
    "a": ["href", "title"],
    "img": ["src", "alt", "title", "width", "height"],
    "code": ["class"],
    "td": ["align"],
    "th": ["align"],
    "div": ["class", "role", "data-copy"],
    "span": ["class"],
    "svg": ["xmlns", "width", "height", "viewBox", "fill", "id",
            "stroke", "stroke-width", "stroke-linecap", "stroke-linejoin",
            "clip-path", "data-name"],
    "g": ["clip-path", "id", "data-name"],
    "clipPath": ["id"],
    "circle": ["cx", "cy", "r"],
    "line": ["x1", "y1", "x2", "y2"],
    "polygon": ["points", "fill"],
    "button": ["class", "aria-label", "data-copy"],
    "rect": ["x", "y", "width", "height", "rx", "ry", "fill", "class",
             "id", "data-name"],
    "path": ["d", "stroke", "stroke-width", "stroke-linecap", "stroke-linejoin",
             "fill", "fill-rule", "clip-rule", "id", "data-name"],
    "linearGradient": ["id", "x1", "y1", "x2", "y2", "gradientUnits"],
    "stop": ["offset", "stop-color", "stop-opacity"],
    "title": [],
    "style": [],
    "defs": [],
"video": ["controls", "preload"],
"source": ["src", "type"],
}
